useDotenv: true
service: todo-api

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-plugin-optimize
  - serverless-dotenv-plugin

provider:
  name: aws
  # stage: dev
  region: ap-northeast-2
  runtime: nodejs18.x
  memorySize: 512
  timeout: 10
  endpointType: REGIONAL

package:
  exclude:
    - .gitignore
    - README.md
    - serverless.yml
    - nest-cli.json
    - .prettierrc
  excludeDevDependencies: true
  individually: true

functions:
  todo:
    handler: apps/todo/src/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors:
            origins:
              - '*'
      - http:
          method: ANY
          cors:
            origins:
              - '*'
          path: "{proxy+}"